### ISSUE TITLE
希望能升级到vue3。

### ISSUE THREAD

**Issue by jiehanlin** [yangfeng727/gantt-chart-vue#1]

**Comment by yangfeng727** [comment]
好的，最近一两月内抽空升下级

**Comment by zf4000** [comment]
@yangfeng727 兄弟,期待你的出手,非常期望vue3+vite版本

**Comment by yangfeng727** [comment]
已升级vue3，地址：https://github.com/yangfeng727/gantt-chart-vue3?tab=readme-ov-file

**Comment by yangfeng727** [comment]
已升级vue3
